name: NuGet v2 mixed-case bug repro (push & pull via /v2/)

on:
  workflow_dispatch: {}          # run manually

permissions:
  contents: read
  id-token: write                # OIDC for Cloudsmith

env:
  CS_ORG:   globex-innovations
  CS_REPO:  acme-nonprod
  SERVICE:  ci_acme_service
  PACKAGE_ID: MyProject          # dummy project name

jobs:
# ------------------------------------------------------------------
# 1) Pack and push THROUGH /v2/  (Ubuntu)
# ------------------------------------------------------------------
  push-v2:
    runs-on: ubuntu-latest
    outputs:
      pkg_version: ${{ steps.meta.outputs.version }}
    steps:
      - uses: actions/checkout@v4

      # OIDC – gives $CLOUDSMITH_API_KEY
      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace:    ${{ env.CS_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only:    'true'

      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: '7.0.x' }

      - name: Create dummy lib
        run: |
          dotnet new classlib -n ${{ env.PACKAGE_ID }}
          mv ${{ env.PACKAGE_ID }} ${{ env.PACKAGE_ID }}.src

      # pack with MIXED-CASE prerelease using run_number
      - name: Pack version
        id: meta
        run: |
          VERSION="1.0.0-CSTEST-${{ github.run_number }}"
          dotnet pack ${{ env.PACKAGE_ID }}.src/${{ env.PACKAGE_ID }}.src.csproj \
            -p:PackageVersion=$VERSION \
            --output ./out
          echo "Packed $VERSION"
          echo "version=$VERSION" >> "$GITHUB_OUTPUT"

      # PUSH via v2  
      - name: Push to Cloudsmith (/v2/)
        continue-on-error: true            # let pipeline carry on after 409
        run: |
          dotnet nuget push ./out/*.nupkg \
          --api-key "$CLOUDSMITH_API_KEY" \
          --source "https://nuget.cloudsmith.io/${{ env.CS_ORG }}/${{ env.CS_REPO }}/v2/" \
          --skip-duplicate
# ------------------------------------------------------------------
# 2) Pull the same package THROUGH /v2/ (Windows) – expected 404
# ------------------------------------------------------------------
  pull-v2:
    needs: push-v2
    runs-on: windows-latest
    
    steps:
      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace:    ${{ env.CS_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only:    'true'

      - name: Add Cloudsmith v2 source
        shell: pwsh
        run: |
          nuget.exe sources Add `
            -Name CloudsmithV2 `
            -Source "https://nuget.cloudsmith.io/${Env:CS_ORG}/${Env:CS_REPO}/v2/" `
            -Username token `
            -Password "$Env:CLOUDSMITH_API_KEY" `
            -StorePasswordInClearText

      - name: Clear cache
        shell: pwsh
        run: nuget.exe locals all -clear

      - name: Install via /v2/
        shell: pwsh
        run: |
          nuget.exe install MyProject `
            -Version 1.0.0-ci.23 `
            -Source CloudsmithV2 `
            -OutputDirectory .\packages `
            -Verbosity detailed

