name: NuGet v2 lowercase-tag test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    
permissions:
  contents: read
  id-token: write

env:
  CS_ORG:   globex-innovations
  CS_REPO:  acme-nonprod
  SERVICE:  ci_acme_service

  PACKAGE_ID:  Microgame.Commission.Domain
  PACKAGE_VER: 12.9.9-cs-test-feature.stsk0132743   # ▼ all lower-case

jobs:
# ───── Build & push via /v2/ ─────
  push-v2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace:   ${{ env.CS_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only:   true
      - uses: actions/setup-dotnet@v3
        with: { dotnet-version: '7.0.x' }

      - run: dotnet new classlib -n "${{ env.PACKAGE_ID }}" --force
      - run: rm -f "${{ env.PACKAGE_ID }}/Program.cs"

      - name: Pack
        run: |
          dotnet pack "${{ env.PACKAGE_ID }}/${{ env.PACKAGE_ID }}.csproj" \
            -p:PackageVersion="${{ env.PACKAGE_VER }}" --output ./out

      - name: Push via /v2/
        continue-on-error: true
        run: |
          dotnet nuget push ./out/*.nupkg \
            --api-key "$CLOUDSMITH_API_KEY" \
            --source "https://nuget.cloudsmith.io/${{ env.CS_ORG }}/${{ env.CS_REPO }}/v2/" \
            --skip-duplicate

# ───── Install the same package via /v2/ (should succeed) ─────
  pull-v2:
    needs: push-v2
    runs-on: windows-latest
    steps:
      - uses: cloudsmith-io/cloudsmith-cli-action@v1.0.2
        with:
          oidc-namespace:   ${{ env.CS_ORG }}
          oidc-service-slug: ${{ env.SERVICE }}
          oidc-auth-only:   true

      - name: Add Cloudsmith v2 source
        shell: pw
